# -*- coding: utf-8 -*-
"""NM Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2wQ1isKiJ_lpjTpEHWKTZhAoiu1mjud
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset (replace with actual patient data)
df = pd.read_csv('diabetes.csv')  # Sample dataset (e.g., Pima Indians Diabetes dataset)

# Preview data
print(df.head())

# Check for nulls
print(df.isnull().sum())

# Correlation heatmap (optional)
sns.heatmap(df.corr(), annot=True)
plt.title("Feature Correlation Heatmap")
plt.show()

# Split data into features and labels
X = df.drop('Outcome', axis=1)  # 'Outcome' is target: 1 = has disease, 0 = no disease
y = df['Outcome']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Random Forest Classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))